export struct XabelFishUiPositionedText {
    text: string,
    width: length,
    height: length,
    x: length,
    y: length,
    font_size: length,
}

export component MainWindow inherits Window {
    in property <string> translation: "Hello, XabelFish!";
    in property <length> fontSize: 30px;
    in property <bool> is_positioned_translation: false;
    in property <[XabelFishUiPositionedText]> positioned_translations: [];
    in property <image> game_image;
    in property <length> game_image_width;
    in property <length> game_image_height;
    preferred-height: 200px;
    preferred-width: 400px;
    always-on-top: true;

    callback start_translation();
    callback stop_translation();

    Image {
        visible: is_positioned_translation;
        source: game_image;
        width: game_image_width;
        height: game_image_height;

        for translation in positioned_translations : Rectangle {
            background: rgba(0, 0, 0, 0.75);
            width: translation.width;
            height: translation.height;
            
            x: translation.x;
            y: translation.y;
            Text {
                text: translation.text;
                font-size: translation.font_size;
                color: white;

                wrap: TextWrap.char-wrap;
                width: translation.width;
                height: translation.height;
            }
        }
    }

    Text {
        text: translation;
        font-size: fontSize;
        visible: !is_positioned_translation;
    }

    MenuBar {
        Menu {
            title: "Translation";
            MenuItem {
                title: "Start";
                activated => {
                    root.start_translation();
                }
            }
            MenuItem {
                title: "Stop";
                activated => {
                    root.stop_translation();
                }
            }
        }
    }
}