[package]
name = "xabelfish_ocr_tesseract"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
xabelfish_unix_socket = { version = "0.1.0", path = "../xabelfish_unix_socket" }
xabelfish_socket_protocol = { version = "0.1.0", path = "../xabelfish_socket_protocol" }
