[package]
name = "xabelfish_engine_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
rustix = { version = "1.1.2", features = ["process"] }
tempfile = "3.23.0"
xabelfish_config = { version = "0.1.0", path = "../xabelfish_config" }
xabelfish_socket_protocol = { version = "0.1.0", path = "../xabelfish_socket_protocol" }
xabelfish_unix_socket = { version = "0.1.0", path = "../xabelfish_unix_socket" }
